export const ADD_ALL_PRODUCTS = "ADD_ALL_PRODUCTS";
export const ADD_ALL_PRODUCTS_SUCCESS = "ADD_ALL_PRODUCTS_SUCCESS";
export const ADD_ALL_PRODUCTS_FAILED = "ADD_ALL_PRODUCTS_FAILED";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";